### ISSUE TITLE
password not matching

### ISSUE THREAD

**Issue by sahil-dhuri** [harsh2527/IBruter#4]
i have tried on my account  ....having right password in passlist thn too its not matching

**Comment by 9Kronos9** [comment]
safe

**Comment by mrRobot0203** [comment]
yes. Its a fake bruter. Good luck finding a real one. I would recommend learning hydra or make your own script

**Comment by harsh2527** [comment]
hey guys this bruter was running on based on an instagram bug which is patched now and it is no longer on development kindly refer the python script i have made its still working @9Kronos9 @sahil-dhuri  

buddy it wasnt a fake bruter just see the date i have uploaded and the date youre using at just by keeping name mrrobot wont make you think like him skiddie get some common sence on how instagram updates and patches there bugs you might be one of them who uses matrix on their screens and say "hey dude i am hacking" XDXDXD skiddie @mrRobot0203
